include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.g.dart"
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_use_package_imports
    - avoid_void_async
    - directives_ordering
    - flutter_style_todos
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
