name: maiporarisu
description: まいぽらりす
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  get: ^4.6.5
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  google_place: ^0.4.7
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^0.13.3
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  google_places_flutter: ^2.0.6
  google_maps_directions: ^0.0.4
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.3
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
